spring.application.name=taphoa2hand-backend
server.port=8080

# Sử dụng biến môi trường, nếu không có thì mặc định là localhost
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/taphoa2hand
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Tương tự cho Redis
redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}

jwt.signed-key=eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJ0YXBob2EyaGFuZC5jb20iLCJzdWIiOiJhZG1pbiIsImV4cCI6MTc3MzgyMjE2MSwiaWF0IjoxNzczODE4NTYxfQ.62TgelCrpdhq44hfVC-GC5vXn57OPCR5ETQEmFKHbXOpyqeNA8lBSS3hhbxF9FiukwxiRYZsCX8vvqEtcbHPXg

jwt.access-token-duration-seconds=86400
jwt.refresh-token-duration-seconds=1296000
jwt.code-duration-seconds=300
app.file.storage-path=D:/upload
app.file.download-prefix=http://localhost:8080/media/download/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lyhoangducuy@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
